package BankingApp;


/**
* BankingApp/BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Thursday, November 7, 2024 1:21:59 PM EAT
*/

public interface BankOperations 
{
  int deposit (int amount);
  int withdraw (int amount);
  int getBalance ();
  void shutdown ();
} // interface BankOperations
