package BankingApp;


/**
* BankingApp/Bank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Thursday, November 7, 2024 1:21:59 PM EAT
*/

public interface Bank extends BankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bank
