package BankingApp;


/**
* BankingApp/BankPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Thursday, November 7, 2024 1:21:59 PM EAT
*/

public abstract class BankPOA extends org.omg.PortableServer.Servant
 implements BankingApp.BankOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("deposit", new java.lang.Integer (0));
    _methods.put ("withdraw", new java.lang.Integer (1));
    _methods.put ("getBalance", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankingApp/Bank/deposit
       {
         int amount = in.read_long ();
         int $result = (int)0;
         $result = this.deposit (amount);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // BankingApp/Bank/withdraw
       {
         int amount = in.read_long ();
         int $result = (int)0;
         $result = this.withdraw (amount);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // BankingApp/Bank/getBalance
       {
         int $result = (int)0;
         $result = this.getBalance ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // BankingApp/Bank/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankingApp/Bank:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Bank _this() 
  {
    return BankHelper.narrow(
    super._this_object());
  }

  public Bank _this(org.omg.CORBA.ORB orb) 
  {
    return BankHelper.narrow(
    super._this_object(orb));
  }


} // class BankPOA
