package BankingApp;

/**
* BankingApp/BankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Thursday, November 7, 2024 1:21:59 PM EAT
*/

public final class BankHolder implements org.omg.CORBA.portable.Streamable
{
  public BankingApp.Bank value = null;

  public BankHolder ()
  {
  }

  public BankHolder (BankingApp.Bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankingApp.BankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankingApp.BankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankingApp.BankHelper.type ();
  }

}
